# Generated by Django 4.2.2 on 2023-11-12 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FullName", models.CharField(max_length=250)),
                ("Email", models.EmailField(max_length=250)),
                ("Phone", models.CharField(max_length=12)),
                ("Update", models.DateTimeField(auto_now=True)),
                ("Created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
